### PR TITLE
GLSG

### PR DESCRIPTION
**Pull request by GODLIKE5**
Plzz change the message to GLSG and send me it. or just tell me how

### CODE REVIEW

**Comment by ifvictr** [comment]
@GODLIKE5 He will not do this. If it is for your own use, then you should modify it for yourself. Learn PHP if you want to change it yourself.

**Comment by GODLIKE5** [comment]
@gamecrafter ik i already did it :P

**Comment by ifvictr** [comment]
@GODLIKE5 No you haven't, you're only making a pull request to do so. Modify your own copy, not the source.

**Comment by GODLIKE5** [comment]
@GameCrafter no look i did
[img] http://postimg.org/image/drqf9bmp3/

**Pull request closed without merging**
